# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20160301_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument',
            new_name='Measurer',
        ),
    ]
