# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20160329_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'отдел', 'verbose_name_plural': 'отделы'},
        ),
        migrations.AlterModelOptions(
            name='measurer',
            options={'verbose_name': 'прибор', 'verbose_name_plural': 'приборы'},
        ),
    ]
