# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160411_1548'),
        ('departments', '0003_auto_20160330_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='report_type',
            field=models.ManyToManyField(to='reports.Report', verbose_name='Виды отчетов, выпускаемые отделом'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название отдела'),
        ),
    ]
