# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_auto_20160411_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='report_type',
            new_name='report_types',
        ),
    ]
