# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20160411_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurer',
            name='expired_at',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='Дата следующей поверки'),
        ),
        migrations.AlterField(
            model_name='measurer',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип (марка)'),
        ),
        migrations.AlterField(
            model_name='measurer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='measurer',
            name='verification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Свидетельство о поверке'),
        ),
    ]
