# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_auto_20160421_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurer',
            options={'ordering': ['name', 'serial_number'], 'verbose_name': 'прибор', 'verbose_name_plural': 'приборы'},
        ),
    ]
