# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование ЛПУ MГ')),
            ],
            options={
                'verbose_name_plural': 'LPU',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование ТГ')),
                ('address', models.CharField(max_length=400, verbose_name='Почтовый адрес')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('fax', models.CharField(max_length=20, verbose_name='Факс')),
                ('director', models.CharField(max_length=50, verbose_name='Генеральный директор')),
            ],
        ),
        migrations.AddField(
            model_name='lpu',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Organization', verbose_name='Наименование ТГ'),
        ),
    ]
