# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 07:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тип')),
                ('exp', models.CharField(max_length=30, verbose_name='Исполнение по взрывозащите')),
                ('temp', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name='Допустимый диапазон температур окружающей среды')),
                ('factory', models.CharField(max_length=50, verbose_name='Завод изготовитель')),
                ('connection', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('s', 'Звезда'), ('t', 'Треугольник')], max_length=50, verbose_name='Соединение фаз'), size=None)),
            ],
        ),
    ]
