# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
        migrations.AddField(
            model_name='lpu',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Organization'),
        ),
    ]
