# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_auto_20160309_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lpu',
            options={'verbose_name_plural': 'LPU'},
        ),
        migrations.AlterField(
            model_name='lpu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование ЛПУ MГ'),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Organization', verbose_name='Наименование ТГ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=400, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='director',
            field=models.CharField(max_length=50, verbose_name='Генеральный директор'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fax',
            field=models.CharField(max_length=20, verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование ТГ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
    ]
