# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_auto_20160401_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lpu',
            options={'verbose_name': 'ЛПУ', 'verbose_name_plural': 'ЛПУ'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
    ]
