# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 10:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.SmallIntegerField(choices=[(1, 'Звезда'), (2, 'Треугольник')], unique=True, verbose_name='Название соединения')),
                ('scheme', models.ImageField(upload_to='', verbose_name='Схема соединения')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тип')),
                ('exp', models.CharField(max_length=30, verbose_name='Исполнение по взрывозащите')),
                ('temp', django.contrib.postgres.fields.ranges.IntegerRangeField(default=(-40, 40), verbose_name='Допустимый диапазон температур окружающей среды')),
                ('scheme', models.ImageField(upload_to='', verbose_name='Конструктивная схема')),
                ('meters', models.ImageField(upload_to='', verbose_name='Толщинометрия')),
                ('connection', models.ManyToManyField(to='engines.Connection', verbose_name='Соединение')),
            ],
        ),
        migrations.CreateModel(
            name='ExClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Наименование исполнения по взрывозащите')),
            ],
            options={
                'verbose_name_plural': 'Ex classes',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование завода')),
            ],
            options={
                'verbose_name_plural': 'Factories',
            },
        ),
        migrations.AddField(
            model_name='engine',
            name='ex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.ExClass', verbose_name='Исполнение по взрывозащите'),
        ),
        migrations.AddField(
            model_name='engine',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.Factory', verbose_name='Завод изготовитель'),
        ),
    ]
