# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.SmallIntegerField(choices=[(1, 'Звезда'), (2, 'Треугольник')], unique=True, verbose_name='Название соединения')),
                ('scheme', models.ImageField(upload_to='', verbose_name='Схема соединения')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тип')),
                ('scheme', models.ImageField(upload_to='', verbose_name='Конструктивная схема')),
                ('meters', models.ImageField(upload_to='', verbose_name='Толщинометрия')),
                ('temp_low', models.SmallIntegerField(verbose_name='Нижняя граница допустимого диапазона температур окружающей среды')),
                ('temp_high', models.SmallIntegerField(verbose_name='Верхняя граница допустимого диапазона температур окружающей среды')),
                ('power', models.FloatField(verbose_name='Номинальная мощность, кВт')),
                ('voltage', models.SmallIntegerField(verbose_name='Номинальное напряжение, В')),
                ('current', models.FloatField(verbose_name='Номинальный ток статора, А')),
                ('freq', models.SmallIntegerField(verbose_name='Номинальная частота вращения, об/мин')),
                ('kpd', models.FloatField(verbose_name='Коэффициент полезного действия, %')),
                ('coef_power', models.FloatField(verbose_name='Коэффициент мощности, cosφ')),
                ('weight', models.SmallIntegerField(verbose_name='Масса двигателя, кг')),
                ('resistance_isolation', models.SmallIntegerField(verbose_name='Сопротивление изоляции, Мом')),
                ('connection', models.ManyToManyField(to='engines.Connection', verbose_name='Соединение')),
            ],
        ),
        migrations.CreateModel(
            name='ExClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Наименование исполнения по взрывозащите')),
            ],
            options={
                'verbose_name_plural': 'Ex classes',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование завода')),
            ],
            options={
                'verbose_name_plural': 'Factories',
            },
        ),
        migrations.CreateModel(
            name='WarmingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(0, 'Y'), (1, 'A'), (2, 'E'), (3, 'B'), (4, 'F'), (5, 'H'), (6, 'C')], unique=True, verbose_name='Обозначение класса нагревостойкости')),
            ],
            options={
                'verbose_name_plural': 'Warming classes',
            },
        ),
        migrations.AddField(
            model_name='engine',
            name='ex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.ExClass', verbose_name='Исполнение по взрывозащите'),
        ),
        migrations.AddField(
            model_name='engine',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.Factory', verbose_name='Завод изготовитель'),
        ),
        migrations.AddField(
            model_name='engine',
            name='warming_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.WarmingClass', verbose_name='Класс нагревостойкости изоляции'),
        ),
    ]
