# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 10:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='temp',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default='(-40, 40)', verbose_name='Допустимый диапазон температур окружающей среды'),
        ),
    ]
