# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0002_auto_20160302_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='temp',
        ),
        migrations.AddField(
            model_name='engine',
            name='temp_high',
            field=models.SmallIntegerField(default=1, max_length=30, verbose_name='Верхняя граница допустимого диапазона температур окружающей среды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='temp_low',
            field=models.SmallIntegerField(default=1, max_length=30, verbose_name='Нижняя граница допустимого диапазона температур окружающей среды'),
            preserve_default=False,
        ),
    ]
