# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0002_thermclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermclass',
            name='t_max',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Максимально допустимая температура поверхности оболочки, °C'),
            preserve_default=False,
        ),
    ]
