# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0003_thermclass_t_max'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thermclass',
            options={'verbose_name_plural': 'Therm classes'},
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_D',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/D'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_L1',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/L1'),
            preserve_default=False,
        ),
    ]
