# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0004_remove_engine_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(unique=True, verbose_name='Обозначение класса нагревостойкости')),
            ],
        ),
        migrations.AddField(
            model_name='engine',
            name='coef_power',
            field=models.FloatField(default=0, verbose_name='Коэффициент мощности, cosφ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='kpd',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100, 'КПД не может превышать 100%')], verbose_name='Коэффициент полезного действия, %'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engine',
            name='temp_high',
            field=models.SmallIntegerField(verbose_name='Верхняя граница допустимого диапазона температур окружающей среды'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='temp_low',
            field=models.SmallIntegerField(verbose_name='Нижняя граница допустимого диапазона температур окружающей среды'),
        ),
    ]
