# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0004_auto_20160316_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_D',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_L1',
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_D_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/D (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_D_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/D (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_L1_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/L1 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_L1_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/L1 (нижний предел)'),
            preserve_default=False,
        ),
    ]
