# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0005_auto_20160316_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_S_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/S (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_S_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/S (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_W1_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/W1 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_W1_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/W1 (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_d_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/d (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_d_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты верхнего подшипникового узла/d (нижний предел)'),
            preserve_default=False,
        ),
    ]
