# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0005_auto_20160302_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='kpd',
            field=models.SmallIntegerField(verbose_name='Коэффициент полезного действия, %'),
        ),
        migrations.AlterField(
            model_name='warmingclass',
            name='name',
            field=models.SmallIntegerField(choices=[(0, 'Y'), (1, 'A'), (2, 'E'), (3, 'B'), (4, 'F'), (5, 'H'), (6, 'C')], unique=True, verbose_name='Обозначение класса нагревостойкости'),
        ),
    ]
