# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0006_auto_20160316_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_D_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/D (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_D_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/D (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_L1_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/L1 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_L1_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/L1 (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_S_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/S (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_S_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/S (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_W1_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/W1 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_W1_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/W1 (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_d_high',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/d (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_d_low',
            field=models.FloatField(default=0, verbose_name='Подвижные взрывонепроницаемые соединения/Узел взрывозащиты нижнего подшипникового узла/d (нижний предел)'),
            preserve_default=False,
        ),
    ]
