# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0006_auto_20160302_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warmingclass',
            options={'verbose_name_plural': 'Warming classes'},
        ),
        migrations.AddField(
            model_name='engine',
            name='resistance_isolation',
            field=models.SmallIntegerField(default=1, verbose_name='Сопротивление изоляции, Мом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='resistance_wire',
            field=models.SmallIntegerField(default=1, verbose_name='Сопротивление обмотки, Ом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='warming_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engines.WarmingClass', verbose_name='Класс нагревостойкости изоляции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='weight',
            field=models.SmallIntegerField(default=1, verbose_name='Масса двигателя, кг'),
            preserve_default=False,
        ),
    ]
