# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0007_auto_20160302_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='current',
            field=models.FloatField(default=1, verbose_name='Номинальный ток статора, А'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='freq',
            field=models.FloatField(default=1, verbose_name='Номинальная частота вращения, об/мин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='power',
            field=models.FloatField(default=1, verbose_name='Номинальная мощность, кВт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='voltage',
            field=models.SmallIntegerField(default=1, verbose_name='Номинальное напряжение, В'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engine',
            name='kpd',
            field=models.FloatField(verbose_name='Коэффициент полезного действия, %'),
        ),
    ]
