# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0007_auto_20160316_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_S_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_S_low',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_S_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_S_low',
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_S',
            field=models.FloatField(default=0, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/S'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_S',
            field=models.FloatField(default=0, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/S'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_L1_high',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/L1 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_L1_low',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/L1 (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_L2_high',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/L2 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_L2_low',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/L2 (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_S',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/S'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_W1_high',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/W1 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_W1_low',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/W1 (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_b_high',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/b (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_b_low',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/b (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_f',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_D_high',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/D (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_D_low',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/D (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_L1_high',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/L1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_L1_low',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/L1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_W1_high',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/W1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_W1_low',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/W1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_d_high',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/d (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_d_low',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/d (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_D_high',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/D (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_D_low',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/D (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_L1_high',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/L1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_L1_low',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/L1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_W1_high',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/W1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_W1_low',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/W1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_d_high',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/d (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_d_low',
            field=models.FloatField(verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/d (нижний предел)'),
        ),
    ]
