# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0008_auto_20160316_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_S',
            field=models.FloatField(default=6.3, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/S'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_S',
            field=models.FloatField(default=6.3, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/S'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_S',
            field=models.FloatField(default=6.3, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/S'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_f',
            field=models.FloatField(default=1.5, verbose_name='Неподвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/f'),
        ),
    ]
