# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0009_auto_20160302_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='resistance_wire',
        ),
    ]
