# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0011_auto_20160316_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_L1_high',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/L1 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_L1_low',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/L1 (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_L2_high',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/L2 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_L2_low',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/L2 (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_S',
            field=models.FloatField(default=6.3, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/S'),
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_W1_high',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/W1 (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_W1_low',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/W1 (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_b_high',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/b (верхний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_b_low',
            field=models.FloatField(default=0, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/b (нижний предел)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_f',
            field=models.FloatField(default=1.5, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/f'),
        ),
    ]
