# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0012_auto_20160316_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_W1_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_W1_low',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_W1_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_W1_low',
        ),
    ]
