# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0013_auto_20160316_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_D_high',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/D (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_D_low',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/D (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_L1_high',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/L1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_L1_low',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/L1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_S',
            field=models.FloatField(blank=True, default=6.3, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/S'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_d_high',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/d (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_bottom_point_d_low',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты нижнего подшипникового узла/d (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_D_high',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/D (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_D_low',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/D (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_L1_high',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/L1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_L1_low',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/L1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_S',
            field=models.FloatField(blank=True, default=6.3, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/S'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_d_high',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/d (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='moveable_Ex_connections_top_point_d_low',
            field=models.FloatField(blank=True, verbose_name='Подвижное взрывонепроницаемое соединение/Узел взрывозащиты верхнего подшипникового узла/d (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_L1_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/L1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_L1_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/L1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_L2_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/L2 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_L2_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/L2 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_S',
            field=models.FloatField(blank=True, default=6.3, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/S'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_W1_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/W1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_W1_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/W1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_b_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/b (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_b_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/b (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_f',
            field=models.FloatField(blank=True, default=1.5, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/f'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_L1_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/L1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_L1_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/L1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_L2_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/L2 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_L2_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/L2 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_S',
            field=models.FloatField(blank=True, default=6.3, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/S'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_W1_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/W1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_W1_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/W1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_b_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/b (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_b_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/b (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_reverse_f',
            field=models.FloatField(blank=True, default=1.5, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит с противоположной приводу стороны/f'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_L1_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/L1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_L1_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/L1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_L2_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/L2 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_L2_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/L2 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_S',
            field=models.FloatField(blank=True, default=6.3, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/S'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_W1_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/W1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_W1_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/W1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_b_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/b (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_b_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/b (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_f',
            field=models.FloatField(blank=True, default=1.5, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/f'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_L1_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/L1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_L1_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/L1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_L2_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/L2 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_L2_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/L2 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_S',
            field=models.FloatField(blank=True, default=6.3, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/S'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_W1_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/W1 (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_W1_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/W1 (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_b_high',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/b (верхний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_b_low',
            field=models.FloatField(blank=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/b (нижний предел)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_f',
            field=models.FloatField(blank=True, default=1.5, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/f'),
        ),
    ]
