# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0016_auto_20160317_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_a_high',
            field=models.FloatField(blank=True, null=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/a (верхний предел)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_cap_shield_a_low',
            field=models.FloatField(blank=True, null=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Крышка узла взрывозащиты - подшипниковый щит со стороны привода/a (нижний предел)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_a_high',
            field=models.FloatField(blank=True, null=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/a (верхний предел)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_krishka_a_low',
            field=models.FloatField(blank=True, null=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - крышка/a (нижний предел)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_a_high',
            field=models.FloatField(blank=True, null=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/a (верхний предел)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='unmoveable_Ex_connections_out_stanina_a_low',
            field=models.FloatField(blank=True, null=True, verbose_name='Неподвижное взрывонепроницаемое соединение/Выводное устройство - станина/a (нижний предел)'),
        ),
    ]
