# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0019_auto_20160317_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_cap_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_cap_low',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_external_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_external_low',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_shield_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_shield_low',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_shield_reverse_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_shield_reverse_low',
        ),
        migrations.AddField(
            model_name='engine',
            name='elements_condition_width_norm_cap',
            field=models.FloatField(default=0, verbose_name='Техническое состояние элементов / Допустимые толщины норма (не менее) / Крышка коробки выводов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='elements_condition_width_norm_external',
            field=models.FloatField(default=0, verbose_name='Техническое состояние элементов / Допустимые толщины норма (не менее) / Наружная оболочка корпуса статора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='elements_condition_width_norm_shield',
            field=models.FloatField(default=0, verbose_name='Техническое состояние элементов / Допустимые толщины норма (не менее) / Подшипниковый щит со стороны привода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='elements_condition_width_norm_shield_reverse',
            field=models.FloatField(default=0, verbose_name='Техническое состояние элементов / Допустимые толщины норма (не менее) / Подшипниковый щит с противоположной приводу стороны'),
            preserve_default=False,
        ),
    ]
