# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0021_auto_20160317_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_cap',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_external',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_shield',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_norm_shield_reverse',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_real_cap_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_real_cap_low',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_real_external_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_real_external_low',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_real_shield_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_real_shield_low',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_real_shield_reverse_high',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='elements_condition_width_real_shield_reverse_low',
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_1_high',
            field=models.FloatField(default=0, verbose_name='Зона контроля 1 / Толщина основного металла, мм (фактическая) / Верхний предел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_1_low',
            field=models.FloatField(default=0, verbose_name='Зона контроля 1 / Толщина основного металла, мм (фактическая) / Нижний предел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_1_real',
            field=models.FloatField(default=0, verbose_name='Зона контроля 1 / Допустимые толщины норма (не менее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_2_high',
            field=models.FloatField(default=0, verbose_name='Зона контроля 2 / Толщина основного металла, мм (фактическая) / Верхний предел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_2_low',
            field=models.FloatField(default=0, verbose_name='Зона контроля 2 / Толщина основного металла, мм (фактическая) / Нижний предел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_2_real',
            field=models.FloatField(default=0, verbose_name='Зона контроля 2 / Допустимые толщины норма (не менее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_3_high',
            field=models.FloatField(default=0, verbose_name='Зона контроля 3 / Толщина основного металла, мм (фактическая) / Верхний предел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_3_low',
            field=models.FloatField(default=0, verbose_name='Зона контроля 3 / Толщина основного металла, мм (фактическая) / Нижний предел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_3_real',
            field=models.FloatField(default=0, verbose_name='Зона контроля 3 / Допустимые толщины норма (не менее)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_4_high',
            field=models.FloatField(default=0, verbose_name='Зона контроля 4 / Толщина основного металла, мм (фактическая) / Верхний предел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_4_low',
            field=models.FloatField(default=0, verbose_name='Зона контроля 4 / Толщина основного металла, мм (фактическая) / Нижний предел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='control_zone_4_real',
            field=models.FloatField(default=0, verbose_name='Зона контроля 4 / Допустимые толщины норма (не менее)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engine',
            name='control_zone_1',
            field=models.SmallIntegerField(choices=[(0, 'подшипниковый щит со стороны привода'), (1, 'крышка коробки выводов'), (2, 'наружная оболочка корпуса статора'), (3, 'подшипниковый щит с противоположной стороны привода')], default=0, verbose_name='Зона контроля 1'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='control_zone_2',
            field=models.SmallIntegerField(choices=[(0, 'подшипниковый щит со стороны привода'), (1, 'крышка коробки выводов'), (2, 'наружная оболочка корпуса статора'), (3, 'подшипниковый щит с противоположной стороны привода')], default=1, verbose_name='Зона контроля 2'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='control_zone_3',
            field=models.SmallIntegerField(choices=[(0, 'подшипниковый щит со стороны привода'), (1, 'крышка коробки выводов'), (2, 'наружная оболочка корпуса статора'), (3, 'подшипниковый щит с противоположной стороны привода')], default=2, verbose_name='Зона контроля 3'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='control_zone_4',
            field=models.SmallIntegerField(choices=[(0, 'подшипниковый щит со стороны привода'), (1, 'крышка коробки выводов'), (2, 'наружная оболочка корпуса статора'), (3, 'подшипниковый щит с противоположной стороны привода')], default=3, verbose_name='Зона контроля 4'),
        ),
    ]
