# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0022_auto_20160318_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='control_zone_1_real',
            new_name='control_zone_1_norm',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='control_zone_2_real',
            new_name='control_zone_2_norm',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='control_zone_3_real',
            new_name='control_zone_3_norm',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='control_zone_4_real',
            new_name='control_zone_4_norm',
        ),
    ]
