# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0023_auto_20160318_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'Соединение', 'verbose_name_plural': 'Соединения'},
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'verbose_name': 'Двигатель', 'verbose_name_plural': 'Двигатели'},
        ),
        migrations.AlterModelOptions(
            name='exclass',
            options={'verbose_name': 'Класс взрывозащиты', 'verbose_name_plural': 'Классы взрывозащиты'},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Завод', 'verbose_name_plural': 'Заводы'},
        ),
        migrations.AlterModelOptions(
            name='thermclass',
            options={'verbose_name': 'Температурный класс', 'verbose_name_plural': 'Температурные классы'},
        ),
        migrations.AlterModelOptions(
            name='warmingclass',
            options={'verbose_name': 'Класс нагревостойкости', 'verbose_name_plural': 'Классы нагревостойкости'},
        ),
    ]
