# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import gmp.filestorage.models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0024_auto_20160514_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='meters',
            field=models.ImageField(storage=gmp.filestorage.models.MediaFileSystemStorage(), upload_to='', verbose_name='Толщинометрия'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='scheme',
            field=models.ImageField(storage=gmp.filestorage.models.MediaFileSystemStorage(), upload_to='', verbose_name='Конструктивная схема'),
        ),
    ]
