# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import gmp.filestorage.models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0025_auto_20160621_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ('connection_type',), 'verbose_name': 'Соединение', 'verbose_name_plural': 'Соединения'},
        ),
        migrations.RemoveField(
            model_name='engine',
            name='connection',
        ),
        migrations.AlterField(
            model_name='connection',
            name='scheme',
            field=models.ImageField(storage=gmp.filestorage.models.MediaFileSystemStorage(), upload_to='', verbose_name='Схема соединения'),
        ),
    ]
