# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='serial_number',
            field=models.CharField(default='0000-aaa-bbb', max_length=20, verbose_name='№ квалификационного удостоверения'),
            preserve_default=False,
        ),
    ]
