# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20160329_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltypes',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Краткое обозначение вида контроля'),
        ),
    ]
