# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_auto_20160329_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='group',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='received_at',
        ),
        migrations.AddField(
            model_name='certificate',
            name='expired_at_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=1, verbose_name='Срок действия (месяц)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='expired_at_year',
            field=models.PositiveSmallIntegerField(default=2010, verbose_name='Срок действия (год)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='received_at_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=1, verbose_name='Дата выдачи (месяц)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='received_at_year',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Дата выдачи (год)'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='control',
        ),
        migrations.AddField(
            model_name='certificate',
            name='control',
            field=models.ManyToManyField(to='certificate.ControlType', verbose_name='Вид контроля'),
        ),
    ]
