# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_auto_20160329_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='control',
            new_name='control_types',
        ),
    ]
