# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificate', '0006_auto_20160329_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBcertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, verbose_name='№ удостоверения по ЭБ')),
                ('received_at', models.DateField(verbose_name='Дата выдачи')),
                ('expired_at', models.DateField(verbose_name='Срок действия')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], verbose_name='Группа ЭБ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
