# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_ebcertificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Удостоверение', 'verbose_name_plural': 'Удостоверения'},
        ),
        migrations.AlterModelOptions(
            name='controltype',
            options={'verbose_name': 'Вид контроля', 'verbose_name_plural': 'Виды контроля'},
        ),
        migrations.AlterModelOptions(
            name='ebcertificate',
            options={'verbose_name': 'Удостоверение по ЭБ', 'verbose_name_plural': 'Удостоверения по ЭБ'},
        ),
        migrations.AlterField(
            model_name='ebcertificate',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
