# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_auto_20160330_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltype',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Полное наименование вида контроля'),
        ),
        migrations.AlterField(
            model_name='controltype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Краткое обозначение вида контроля'),
        ),
    ]
