# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_auto_20160413_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='degree',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='controltype',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное наименование вида контроля'),
        ),
    ]
