# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование вида очета')),
                ('url', models.URLField(verbose_name='Ссылка на страницу формирования отчета в веб-интерейсе')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание очета')),
            ],
        ),
    ]
