# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160411_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание очета'),
        ),
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.URLField(default='', verbose_name='Ссылка на страницу формирования отчета в веб-интерейсе'),
            preserve_default=False,
        ),
    ]
