# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20160411_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterField(
            model_name='report',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Ссылка на страницу формирования отчета в веб-интерейсе'),
        ),
    ]
