# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 2, 9, 11, 11, 16, 451524, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
