# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=models.SET('Отдел не выбран'), to='authentication.Department'),
        ),
    ]
