# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160210_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.Department'),
        ),
    ]
