# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160321_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name', 'middle_name']},
        ),
    ]
