# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20160301_1303'),
        ('authentication', '0007_auto_20160224_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
