# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='Storage',
        ),
    ]
