# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import gmp.filestorage.models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0002_auto_20160408_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='name',
        ),
        migrations.AddField(
            model_name='storage',
            name='orig_file',
            field=models.FileField(blank=True, null=True, upload_to=gmp.filestorage.models.get_hash_path),
        ),
    ]
