# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0003_auto_20160408_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='orig_file',
            new_name='fileupload',
        ),
    ]
