# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0005_auto_20160408_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='md5_sum',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
