# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0006_storage_md5_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
