# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gmp.filestorage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filestorage', '0007_storage_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileupload', models.FileField(storage=gmp.filestorage.models.MediaFileSystemStorage(), upload_to=gmp.filestorage.models.get_hash_path)),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('md5_sum', models.CharField(blank=True, max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='storage',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
