# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0008_auto_20160411_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filestorage',
            old_name='filename',
            new_name='name',
        ),
    ]
