# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0009_auto_20160411_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorage',
            name='md5_sum',
        ),
        migrations.RemoveField(
            model_name='filestorage',
            name='name',
        ),
    ]
