# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import gmp.filestorage.models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0011_auto_20160621_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='fileupload',
            field=models.FileField(max_length=400, storage=gmp.filestorage.models.MediaFileSystemStorage(), upload_to=''),
        ),
    ]
