# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name': 'Носитель', 'verbose_name_plural': 'Носители'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Сосуд', 'verbose_name_plural': 'Сосуды'},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'Контроль', 'verbose_name_plural': 'Контроль'},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Завод-изготовитель', 'verbose_name_plural': 'Заводы-изготовители'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='welding',
            options={'verbose_name': 'Сварка', 'verbose_name_plural': 'Сварка'},
        ),
        migrations.RemoveField(
            model_name='container',
            name='temp_carrier',
        ),
        migrations.AddField(
            model_name='container',
            name='temp_carrier_high',
            field=models.SmallIntegerField(default=1, verbose_name='Рабочая температура среды (верхняя граница), ⁰С'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='temp_carrier_low',
            field=models.SmallIntegerField(default=1, verbose_name='Рабочая температура среды (нижняя граница), ⁰С'),
            preserve_default=False,
        ),
    ]
