# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_auto_20160411_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='factory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='containers.Factory', verbose_name='Завод-изготовитель'),
        ),
    ]
