# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_auto_20160411_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='carrier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='containers.Carrier', verbose_name='Технологическая среда'),
        ),
        migrations.AlterField(
            model_name='container',
            name='control',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='containers.Control', verbose_name='Контроль при изготовлении'),
        ),
        migrations.AlterField(
            model_name='container',
            name='material_bottom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_bottom', to='containers.Material', verbose_name='Материал днища'),
        ),
        migrations.AlterField(
            model_name='container',
            name='material_ring',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_ring', to='containers.Material', verbose_name='Материал обечайки'),
        ),
        migrations.AlterField(
            model_name='container',
            name='welding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='containers.Welding', verbose_name='Сведения о сварке'),
        ),
    ]
