# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_auto_20160412_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='desc',
        ),
    ]
