# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_remove_container_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип сосуда'),
        ),
        migrations.AlterField(
            model_name='container',
            name='inv_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='container',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место установки'),
        ),
        migrations.AlterField(
            model_name='container',
            name='manufactured_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год изготовления'),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Обозначение сосуда'),
        ),
        migrations.AlterField(
            model_name='container',
            name='reg_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='container',
            name='scheme',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер чертежа'),
        ),
        migrations.AlterField(
            model_name='container',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='container',
            name='started_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год ввода в эксплуатацию'),
        ),
    ]
