# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0008_auto_20160606_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='_type',
            field=models.CharField(default='', max_length=50, verbose_name='Тип сосуда'),
            preserve_default=False,
        ),
    ]
