# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0009_auto_20160606_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=100, verbose_name='Тип сосуда')),
            ],
            options={
                'verbose_name': 'Тип сосуда',
                'verbose_name_plural': 'Типы сосудов',
            },
        ),
        migrations.RemoveField(
            model_name='container',
            name='_type',
        ),
    ]
