# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0010_auto_20160607_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='containers.ContainerType', verbose_name='Тип сосуда'),
        ),
    ]
