# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0011_container__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='_type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='containers.ContainerType', verbose_name='Тип сосуда'),
            preserve_default=False,
        ),
    ]
