# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0012_auto_20160607_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='inv_number',
        ),
        migrations.RemoveField(
            model_name='container',
            name='location',
        ),
        migrations.RemoveField(
            model_name='container',
            name='manufactured_year',
        ),
        migrations.RemoveField(
            model_name='container',
            name='reg_number',
        ),
        migrations.RemoveField(
            model_name='container',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='container',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='container',
            name='started_year',
        ),
    ]
